---
 tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
      
  - name: http
    package:
      name: httpie
      state: latest

  - name: start apache
    service:
      name: httpd
      state: started

  - name: enable apache at boot
    service:
      name: httpd
      enabled: yes
      
